dist: trusty
sudo: true
language: c


env:
  global:
    - PATH=/usr/mingw-w64-i686/bin:/usr/mingw-w64-x86_64/bin:${PATH}


before_install:
  - sudo dpkg --purge cmake cmake-doc cmake-data
  - curl --location --silent http://download.opensuse.org/repositories/home:doc_bacardi/xUbuntu_14.04/Release.key | apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_14.04/ /" > /etc/apt/sources.list.d/build_opensuse_org_home_docbacardi.list
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install cmake3 curl gcc g++ git lib32z1 make mingw-w64-mbs python2.7 swig3


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - ./.build01_netx_firmware.sh
  - ./.build02_windows32.sh
  - ./.build03_windows64.sh
  - ./.build04_linux.sh
